### ISSUE TITLE
Log not going to sumo logic

### ISSUE THREAD

**Issue by PradeepJaiswar** [helix-collective/node-sumologic#4]
```
import request from 'request';
import SumoLogger from 'sumologic';

var endpoint = "https://endpoint1.collection.us2.sumologic.com/receiver/v1/http/";
var syncInterval = 1000;
// Optional opts
var opts = {
   request,
   endpoint,
  syncInterval
};
var logger = new SumoLogger('MY_SECRET_COLLECTOR_CODE', opts );

logger.log("Yeah, it worked");

```

Above code don't seems to be working, is i am missing something basic here ?

curl post for same details are working.

**Comment by jsuresh** [comment]
Apologies for the late reply @PradeepJaiswar - I missed the notification for this issue.

Your approach works fine for me. Assuming your 'opts' structure is a typo (it's meant to be a map). eg.

```
var opts = {
  endpoint: endpoint,
}
```
