### ISSUE TITLE
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

### ISSUE THREAD

**Issue by cogit8** [helix-collective/node-sumologic#7]
Hello, the version of 'request' used by node-sumologic has a dependency on 'node-uuid' which is now deprecated. 'request' itself has been updated to use the 'uuid' module. Can you please bump the version of 'request' in package.json so node-sumologic pulls in an updated version of 'request' and avoids this warning. Thanks.

**Comment by jsuresh** [comment]
Thanks @cogit8 this has been done
